import 'package:flutter/material.dart';

class AppColorSchemes {
  // Default Light Color Scheme (Material 3)
  static const ColorScheme defaultLightScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF6750A4),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFEADDFF),
    onPrimaryContainer: Color(0xFF21005D),
    secondary: Color(0xFF625B71),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE8DEF8),
    onSecondaryContainer: Color(0xFF1D192B),
    tertiary: Color(0xFF7D5260),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFD8E4),
    onTertiaryContainer: Color(0xFF31111D),
    error: Color(0xFFB3261E),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFF9DEDC),
    onErrorContainer: Color(0xFF410E0B),
    surface: Color(0xFFFFFBFE),
    onSurface: Color(0xFF1C1B1F),
    surfaceContainerHighest: Color(0xFFE7E0EC),
    onSurfaceVariant: Color(0xFF49454F),
    outline: Color(0xFF79747E),
    outlineVariant: Color(0xFFCAC4D0),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF313033),
    onInverseSurface: Color(0xFFF4EFF4),
    inversePrimary: Color(0xFFD0BCFF),
  );

  // Default Dark Color Scheme (Material 3)
  static const ColorScheme defaultDarkScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFD0BCFF),
    onPrimary: Color(0xFF381E72),
    primaryContainer: Color(0xFF4F378B),
    onPrimaryContainer: Color(0xFFEADDFF),
    secondary: Color(0xFFCCC2DC),
    onSecondary: Color(0xFF332D41),
    secondaryContainer: Color(0xFF4A4458),
    onSecondaryContainer: Color(0xFFE8DEF8),
    tertiary: Color(0xFFEFB8C8),
    onTertiary: Color(0xFF492532),
    tertiaryContainer: Color(0xFF633B48),
    onTertiaryContainer: Color(0xFFFFD8E4),
    error: Color(0xFFF2B8B5),
    onError: Color(0xFF601410),
    errorContainer: Color(0xFF8C1D18),
    onErrorContainer: Color(0xFFF9DEDC),
    surface: Color(0xFF1C1B1F),
    onSurface: Color(0xFFE6E1E5),
    surfaceContainerHighest: Color(0xFF49454F),
    onSurfaceVariant: Color(0xFFCAC4D0),
    outline: Color(0xFF938F99),
    outlineVariant: Color(0xFF49454F),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFE6E1E5),
    onInverseSurface: Color(0xFF313033),
    inversePrimary: Color(0xFF6750A4),
  );

  // Food Theme Light (Greens and warm tones)
  static const ColorScheme foodLightScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF4CAF50),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFC8E6C9),
    onPrimaryContainer: Color(0xFF1B5E20),
    secondary: Color(0xFFFF9800),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFE0B2),
    onSecondaryContainer: Color(0xFFE65100),
    tertiary: Color(0xFFFF5722),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFCCBC),
    onTertiaryContainer: Color(0xFFBF360C),
    error: Color(0xFFD32F2F),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFCDD2),
    onErrorContainer: Color(0xFFB71C1C),
    surface: Color(0xFFFFFBF5),
    onSurface: Color(0xFF1F1F1F),
    surfaceContainerHighest: Color(0xFFE8F5E9),
    onSurfaceVariant: Color(0xFF424242),
    outline: Color(0xFF81C784),
    outlineVariant: Color(0xFFC8E6C9),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF2E2E2E),
    onInverseSurface: Color(0xFFF5F5F5),
    inversePrimary: Color(0xFF81C784),
  );

  // Food Theme Dark
  static const ColorScheme foodDarkScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF81C784),
    onPrimary: Color(0xFF1B5E20),
    primaryContainer: Color(0xFF388E3C),
    onPrimaryContainer: Color(0xFFC8E6C9),
    secondary: Color(0xFFFFB74D),
    onSecondary: Color(0xFFE65100),
    secondaryContainer: Color(0xFFF57C00),
    onSecondaryContainer: Color(0xFFFFE0B2),
    tertiary: Color(0xFFFF8A65),
    onTertiary: Color(0xFFBF360C),
    tertiaryContainer: Color(0xFFE64A19),
    onTertiaryContainer: Color(0xFFFFCCBC),
    error: Color(0xFFEF5350),
    onError: Color(0xFFB71C1C),
    errorContainer: Color(0xFFC62828),
    onErrorContainer: Color(0xFFFFCDD2),
    surface: Color(0xFF1A1A1A),
    onSurface: Color(0xFFE8E8E8),
    surfaceContainerHighest: Color(0xFF2E3B2E),
    onSurfaceVariant: Color(0xFFC8E6C9),
    outline: Color(0xFF66BB6A),
    outlineVariant: Color(0xFF2E3B2E),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFE8E8E8),
    onInverseSurface: Color(0xFF2E2E2E),
    inversePrimary: Color(0xFF4CAF50),
  );
}

enum ColorPalette {
  defaultPalette,
  foodTheme,
}
